blueprint:
  name: Layer-Based AUX Fan Control
  description: >
    456Control the AUX fan speed of a Bambu Lab P1S/X1C 3D printer based on the current layer.

    Specify fan speed settings in the format `[percentage:layer]`, `[percentage:layer_start-layer_end]`, `[layer]`, or `[layer_start-layer_end]`.

    Multiple settings can be combined by separating them with commas.

    For example: `[50:195-210]`, `[60:220-230]`, `[70:250]`.

  domain: automation
  input:
    printer_layer_sensor:
      name: Printer Current Layer Sensor Entity
      description: Sensor entity that provides the current layer of the print job.
      selector:
        entity:
          domain: sensor
    printer_fan_control:
      name: Printer AUX Fan Control Entity
      description: Fan entity to control the printer's AUX fan power and speed.
      selector:
        entity:
          domain: fan
    printer_fan_speed_sensor:
      name: Printer AUX Fan Speed Sensor Entity
      description: Sensor entity that provides the current AUX fan speed.
      selector:
        entity:
          domain: sensor
    fan_speed_settings:
      name: Fan Speed Settings
      description: >
        Specify fan speed settings in the format `[layer_start]`, `[percentage:layer_start]`, `[layer_start-layer_end]`, or `[percentage:layer_start-layer_end]`.

        Multiple settings can be combined by separating them with commas.

        For example: `[50:195-210]`, `[60:220-230]`, `[70:250]`.

      default: "[50:190-210]"
      selector:
        text:
    default_fan_percentage:
      name: Default Fan Percentage
      description: >
        The default fan speed percentage to use when no percentage is specified in a setting.
      default: 70
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: slider
trigger:
  - platform: state
    entity_id: !input printer_layer_sensor
action:
  - variables:
      current_layer: "{{ states( trigger.entity_id ) | int(0) }}"
      fan_settings_str: !input fan_speed_settings
      default_fan_percentage: !input default_fan_percentage
      fan_speed_sensor: !input printer_fan_speed_sensor
      current_fan_speed: "{{ states( fan_speed_sensor ) | int(0) }}"
      fan_settings_list: >
        {% set pattern = '\[(?:(\d+):)?(\d+)(?:-(\d+))?\]' %}
        {% set fan_settings = [] %}
        {% for setting in fan_settings_str.split(',') %}
          {% set setting = setting.strip() %}
          {% set matches = setting | regex_findall(pattern) %}
          {% for match in matches %}
            {% set percentage = match[0] %}
            {% set layer_start = match[1] %}
            {% set layer_end = match[2] if match[2] != '' else match[1] %}
            {% set percentage = percentage | int if percentage != '' else None %}
            {% set fan_settings = fan_settings + [ { 'percentage': percentage, 'layer_start': layer_start | int, 'layer_end': layer_end | int } ] %}
          {% endfor %}
        {% endfor %}
        {{ fan_settings }}
  - variables:
      current_percentage: >
        {% set current_percentage = 0 %}
        {% for setting in fan_settings_list %}
          {% if current_layer >= setting.layer_start and current_layer <= setting.layer_end %}
            {% if setting.percentage is not none %}
              {% set current_percentage = setting.percentage %}
            {% else %}
              {% set current_percentage = default_fan_percentage | int %}
            {% endif %}
            {% break %}
          {% endif %}
        {% endfor %}
        {{ current_percentage }}
  - service: system_log.write
    data:
      level: info
      message: >
        AUX Fan Control Debug:
        current_layer: {{ current_layer }},
        current_percentage: {{ current_percentage }},
        current_fan_speed: {{ current_fan_speed }},
        fan_settings_list: {{ fan_settings_list }}
  - choose:
      - conditions:
          - "{{ current_percentage | int > 0 }}"
          - "{{ current_fan_speed | int != current_percentage | int }}"
        sequence:
          - choose:
              - conditions: "{{ current_fan_speed | int == 0 }}"
                sequence:
                  - service: fan.turn_on
                    target:
                      entity_id: !input printer_fan_control
          - service: fan.set_percentage
            target:
              entity_id: !input printer_fan_control
            data:
              percentage: "{{ current_percentage }}"
      - conditions:
          - "{{ current_percentage | int == 0 }}"
          - "{{ current_fan_speed | int != 0 }}"
        sequence:
          - service: fan.turn_off
            target:
              entity_id: !input printer_fan_control
